Settings:
  ResetKSOnMobKill: true
  PlaceholderRefresh: 35 #in seconds
  AntiAbuse: 3 #after 3 kills from same person, you will stop receiving kills
Messages:
  Killstreaks: "&7----------------------\n
    &7[&6KillstreakSystem&7]\n
    &4Stats of player: &7%player\n
    &4Current KS: &7%currentKs\n
    &4Biggest KS: &7%biggestKs\n
    &4Award for killing: &7%award\n
  &7----------------------"
  NoPermission: "&7[&6KillstreakSystem&7] &4You don't have permission to execute this command"
  Reload: "&7[&6KillstreakSystem&7] &4Config is successful reloaded!"
  NotInDatabase: "&7[&6KillstreakSystem&7] &4Sorry, but player %player is not in our database"
  SetWrongUsage: "&7[&6KillstreakSystem&7] &4Wrong usage, correct usage is /killstreaks set <player> <killstreak>"
  SetNotNumber: "&7[&6KillstreakSystem&7] &4 Third arg must be a number"
  SetSuccess: "&7[&6KillstreakSystem&7] &4You successfully set killstreak of player %player to %killstreak"
  RestoreKS: "&7[&6KillstreakSystem&7] &4You successfully restored killstreak of player %player "
  RestoreKSTarget: "&7[&6KillstreakSystem&7] &4Your killstreak is restored by %player "