name: KillStreakSystem
version: '${project.version}'
main: tech.goksi.killstreaksystem.Main
authors: [ Goksi ]
description: Cool killstreaks plugin with killing rewards and placeholderapi support
website: https://goksi.tech
commands:
  killstreaks:
    aliases: [killstreak]
    description: Main command for plugin
permissions:
  killstreaks.reload:
    description: Permission to reload configuration
    default: op
  killstreaks.set:
    description: Sets killstreak of another player
    default: op
  killstreaks.restore:
    description: Restore killstreak of another player
    default: op
